#Python NumPy: Arrays and Vectorized Computation

This is a personal study note for Data Wrangling. It is meant to be a both a quick guide and reference for further research into these topics. 

*Reference: Python for Data Analysis by Wes McKinny*

##Array

A numpy array is a grid of values, all of the **same type**, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the **shape** of an array is a tuple of integers indicating the size of each dimension.

The easiest way to create an array is to use the *array* function. This accepts any se- quence-like object (including other arrays) and produces a new NumPy array containing the passed data.


In [8]:
import numpy as np
a = np.array([1, 2, 3])  # Create a rank 1 array
print type(a), a.ndim, a.shape, a[0], a[1], a[2]            

<type 'numpy.ndarray'> 1 (3,) 1 2 3


In [5]:
a[0] = 5                 # Change an element of the array
print a     

[5 2 3]


In [9]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print b

[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [10]:
print b.ndim, b.shape

2 (2, 3)


##Datatypes

Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. 

In [13]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
z = x.astype(np.float64)  #Cast an array from one dtype to another 

print x.dtype, y.dtype, z.dtype

int64 int64 float64


More dtype: [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)

##Array Indexing